---
title: "Dashboard: NYC Restuarant Inspection (2015-2024)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: flatly
---

```{r include = FALSE,message=FALSE,warning=FALSE}
library(flexdashboard)
library(tidyverse)
library(httr)
library(jsonlite)
library(plotly)
library(sf)


knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Column {data-width=350}
-----------------------------------------------------------------------

```{r, message = FALSE, echo = FALSE, include=FALSE}
get_all_inspections = function(url) {
  
  all_inspections = vector("list", length = 0)
  
  loop_index = 1
  chunk_size = 50000
  DO_NEXT = TRUE
  
  while (DO_NEXT) {
    message("Getting data, page ", loop_index)
    
    all_inspections[[loop_index]] = 
      GET(url,
          query = list(`$order` = "zipcode",
                       `$limit` = chunk_size,
                       `$offset` = as.integer((loop_index - 1) * chunk_size)
                       )
          ) %>%
      content("text") %>%
      fromJSON() %>%
      as_tibble()
    
    DO_NEXT = dim(all_inspections[[loop_index]])[1] == chunk_size
    loop_index = loop_index + 1
  }
  
  all_inspections
  
}
url = "https://data.cityofnewyork.us/resource/43nn-pn8j.json"

nyc_inspections <-  get_all_inspections(url) %>%
  bind_rows() 
```

```{r}
nyc_inspections_df <- nyc_inspections |> 
  mutate(boro = case_when(boro == 0 ~ NA, 
                          TRUE ~ boro), 
         critical_flag = case_when(critical_flag == "Not Applicable" ~ "No Violation", 
                          TRUE ~ critical_flag), 
         inspection_date = case_when(inspection_date == "1900-01-01T00:00:00.000" ~ NA, 
                          TRUE ~ inspection_date),
         latitude = case_when(latitude == "0" ~ NA, 
                              TRUE ~ as.numeric(latitude)), 
         longitude =  case_when(longitude == "0" ~ NA, 
                              TRUE ~ as.numeric(longitude)), 
         score = as.numeric(score))

```

### Chart A: Average number of inspections per restaurant

```{r, echo = FALSE}
score_distribution <- 
  nyc_inspections_df |>
  group_by(camis, longitude, latitude) |> 
  summarize(average_score = mean(score, na.rm = TRUE)) |> 
  ungroup() |> 
  drop_na(average_score) |> 
  ggplot(aes(x = latitude, y = longitude, color = average_score)) + 
  geom_point(alpha = 0.6, size = 1) +
  #scale_color_gradient(high = "darkred", low = "white")+
  coord_cartesian()+
  theme_classic()

ggplotly(score_distribution)
```

Column {data-width=6500}
-----------------------------------------------------------------------

### Chart B: Code Violation Categories

```{r, echo = FALSE}
nyc_inspections_df |> 
  drop_na(critical_flag) |> 
  count(boro, critical_flag) |> 
  ggplot(aes(fill = critical_flag, x = n, group = boro, fill = boro)) +
  geom_density(alpha = 0.5)

```

### Chart C

```{r, echo = FALSE}

```